### ISSUE TITLE
Module NullException is missing 

### ISSUE THREAD

**Issue by M1d0ri** [NullExceptionTSB/Haemolacria#1]
Hello there,
Aeroplane was working properly until a few days ago when the module NullException went missing for no apparent reason, and i can't find it anywhere.

It's a critical element in aeroplane and nothing appears to work properly without it.

Could you please provide it ?

I opened a new pseudo-permanent xmpp server :
IP : 185.163.126.95
or
Domain : yuri.life

Registrations are currently open, join "general" channel for more info.

-Midori

PS: ily <3

**Comment by NullExceptionTSB** [comment]
midori mabye not on a public repo lol

**Comment by NullExceptionTSB** [comment]
btw ily too
